# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e6faa47ac0cc4d2b9e455cb4699ae52a9eb24ed91efb976266ec0ba146abc47e938609bf09fa106fd731160dfe72dfb5e5877bd475bdb1da1b36d998f07caac

test:
  secret_key_base: f8a0cc999f2639d17db4a962a74ca8ad768e3d7cba642c5a71f6a21e10a4c3663d5061c6dc555c76bc79f6c442ec29a5465142fec02238979a85b25f1efad50a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
